language: node_js
node_js:
- '5'
deploy:
  on:
    tags: true
  provider: npm
  api_key:
    secure: Ma7xPECa517Wm//a8hjLsR48AmfWQDxU1cm5ZNkT7ZUUMnRwIn8RsvLpB7mknQUC5TWDQbaVsyMlWLn09vEnvJDzUpVT63Q300VweB3fs/I4Uz13Oj5uiSVNFp7K37rSQ/0ec65+yzRNxq0C9W2+lVPCCSiViJE2pGZ6SwDAfiHtPz/ubuTkwoZe4nbFfppVUnqcdkK/uvmAEEwLEPg9nl8288Rm3spRsc9w07TGej89L9fhCWiVTHpnkmHCoxT/zErxCMAun6QMIleGJpGPZExyWZk3rPGaCh+8IQ/0QX0TNU89fy6Y1+gEreCXRKfOlZG98thynzovNJJMHk0BVqaJf6wWtVILn6Ov0m/Fxs69HpUoZbw9MjA0nNKrTyLcNSSQ4/BEzprWXiSYBbDf10hgCPFzkrsBxzXGwLTRCRR8PMaLSKgRdAdqX3H6bn8UvOXQZHR1R7wVafckVMgb5ZUNBwkYXT26NKFf75Hz4rQJnLCES3b/4G0mF4eXjheVbsAHYTxBSelRSREcHoAHYnR8uS76ZYuQ3LijzqTdUjl3xGa8B5Z5QjTDrL8q+gszzeSsUdOOvr0K6lIfrX3WqXnffdOt6HdGYgV3UH5zndFURBZZNaHiMck+FKyFH4yWEZZ0ZXee71b3L/VO1JGbYDzxUV6Dg7d/W5qAsAkvWb0=
